title: Portfolio
name: Won il jun
email: sumusb34@gmail.com
description: Java Back-end Developer

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/image2.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/image2.jpg

project_one: OnePage
project_one_description: 위치 기반 익명 SNS <br/><br/> Back-end -> Spring Boot, JPA<br/> DB -> mySql
project_one_url: https://github.com/iljun/OnePageServer
project_one_icon: location_on
project_one_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/onePage/

project_two: SHKU_Assosiation
project_two_description: 교내 동문회 관리 시스템 <br/><br/> Front-end -> Html5, CSS3, JavaScript, Bootstrap3 <br/> Back-end -> Spring Boot, JPA, QueryDSL <br/>DB -> mySql
project_two_url: https://github.com/iljun/SKHU_Association
project_two_icon: photo_camera
project_two_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/skhu/

project_three: Naver winter Hack Day ShortingUrl
project_three_description: 단축 URL <br/><br/> Front-end -> JSP, JSTL <br/> Beack-end -> Spring Boot, JPA, Apache, EhCache <br/> DB -> mySql
project_three_url: 
project_three_icon: hotel
project_three_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/hackathon/naverWinter/

project_four: Naver winter Intern - Admin
project_four_description: Admin refactoring <br/><br/> Front-end -> Angular4, Html5, CSS3, Bootstrap4, , localStorage, JavaScript <br/> Back-end -> Spring Boot, myBatis, mySql <br/> DB -> mySql 
project_four_url: 
project_four_icon: restaurant
project_four_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/naver/admin/

project_five: Naver winter Intern - demoSite V1
project_five_description: Embeded Editor DemoSite V1 <br/><br/> Front-end -> Html5, CSS3, Bootstrap4, localStorage, JavaScript 
project_five_url: 
project_five_icon: restaurant
project_five_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/naver/demoSite-v1/

project_six: Naver winter Intern - demoSite V2
project_six_description: Embeded Editor DemoSite V2 <br/><br/> Front-end -> Html5, CSS3, Bootstrap4, sessionStorage, JavaScript <br/> Back-end -> Spring Boot, myBatis, mySql <br/> DB -> mySql 
project_six_url: 
project_six_icon: restaurant
project_six_description_url: https://iljun.gitbooks.io/iljun-portfolio/content/naver/demoSite-v2/

project_seven: Simple Blog
project_seven_description: Simple Blog <br/><br/> Front-end -> Angular4 <br/> Back-end -> Spring Boot, JPA, OAuth2.0, JWT <br/> DB -> mySql <br/> 아직 개발중입니다...
project_seven_url: https://github.com/iljun/simple-blog
project_seven_icon: restaurant
project_seven_description_url:

project_eight: DevNote
project_eight_description: DevNote <br/>
project_eight_url: https://github.com/iljun/DevNote
project_eight_icon: photo_camera
project_eight_description_url: https://iljun.gitbooks.io/devnote/content/

project_nine: Algorithm study
project_nine_description: Alogrithm <br/><br/> Language -> Java
project_nine_url: https://github.com/iljun/Algorithm
project_nine_icon: location_on
project_nine_description_url:
  
portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  # - name: amazonwebservices
  # - name: android
  # - name: angularjs
  - name: apache
  # - name: appcelerator
  # - name: apple
  - name: atom
  # - name: babel
  # - name: backbonejs
  # - name: bitbucket
  - name: bootstrap
  # - name: bower
  # - name: c
  - name: chrome
  # - name: codeigniter
  # - name: coffescript
  # - name: confluence
  # - name: cplusplus
  # - name: csharp
  - name: css3
  # - name: cucumber
  # - name: d3js
  # - name: debian
  # - name: devicon
  # - name: django
  # - name: docker
  # - name: doctrine
  # - name: dot-net
  # - name: drupal
  # - name: erlang
  - name: facebook
  - name: firefox
  # - name: foundation
  # - name: gatling
  # - name: gimp
  - name: git
  - name: github
  # - name: gitlab
  # - name: go
  - name: google
  - name: gradle
  # - name: grunt
  # - name: gulp
  # - name: heroku
  - name: html5
  - name: ie10
  # - name: illustrator
  # - name: inkscape
  - name: itellij
  - name: java
  # - name: jasmine
  - name: javascript
  # - name: laravel
  # - name: less
  - name: linux
  # - name: meteor
  # - name: mocha
  - name: mongodb
  # - name: moodle
  - name: mysql
  # - name: nginx
  - name: nodejs
  # - name: nodewebkit
  - name: oracle
  # - name: photoshop
  # - name: php
  # - name: phpstorm
  # - name: protractor
  # - name: postgresql
  # - name: python
  # - name: pycharm
  # - name: rails
  # - name: react
  # - name: redhat
  # - name: redis
  # - name: ruby
  # - name: rubymine
  - name: safari
  # - name: sass
  # - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  # - name: swift
  # - name: symfony
  - name: tomcat
  - name: travis
  # - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  # - name: visualstudio
  # - name: vuejs
  # - name: webpack
  # - name: webstorm
  - name: windows8
  # - name: wordpress
  # - name: yii
  # - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/iljun
medium: https://developnote.gitbook.io/project/

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: https://iljun.github.io/protfolio/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
