title: Protfolio
name: Won il jun
email: sumusb34@gmail.com
description: Java Back-end Developer

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: OnePage
project_one_description: 위치 기반 익명 SNS <br/> Spring Boot, JPA, mySql
project_one_url: https://github.com/iljun/OnePageServer
project_one_icon: photo_camera

project_two: SHKU_Assosiation
project_two_description: 교내 동문회 관리 시스템 <br/> Spring Boot, JPA, mySql, QueryDSL
project_two_url: https://github.com/iljun/SKHU_Association
project_two_icon: photo_camera


project_three: Naver winter Hack Day ShortingUrl
project_three_description: 단축 URL <br/> Spring Boot, JPA, mySql, Apache, EhCache
project_three_url: 
project_three_icon: hotel

project_four: Naver winter Intern
project_four_description: Admin refactoring <br/> Angular4, Spring Boot, myBatis, mySql, localStorage, JavaScript 
project_four_url: 
project_four_icon: restaurant

project_four: Simple Blog
project_four_description: Simple Blog <br/> Angular4, Spring Boot, JPA, mySql, JWT
project_four_url: https://github.com/iljun/simple-blog
project_four_icon: restaurant

project_four: Algorithm study
project_four_description: Alogrithm <br/> Java
project_four_url: https://github.com/iljun/Algorithm
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  # - name: amazonwebservices
  # - name: android
  # - name: angularjs
  - name: apache
  # - name: appcelerator
  # - name: apple
  - name: atom
  # - name: babel
  # - name: backbonejs
  # - name: bitbucket
  - name: bootstrap
  # - name: bower
  # - name: c
  - name: chrome
  # - name: codeigniter
  # - name: coffescript
  # - name: confluence
  # - name: cplusplus
  # - name: csharp
  - name: css3
  # - name: cucumber
  # - name: d3js
  # - name: debian
  # - name: devicon
  # - name: django
  # - name: docker
  # - name: doctrine
  # - name: dot-net
  # - name: drupal
  # - name: erlang
  - name: facebook
  - name: firefox
  # - name: foundation
  # - name: gatling
  # - name: gimp
  - name: git
  - name: github
  # - name: gitlab
  # - name: go
  - name: google
  - name: gradle
  # - name: grunt
  # - name: gulp
  # - name: heroku
  - name: html5
  - name: ie10
  # - name: illustrator
  # - name: inkscape
  - name: itellij
  - name: java
  # - name: jasmine
  - name: javascript
  # - name: laravel
  # - name: less
  - name: linux
  # - name: meteor
  # - name: mocha
  - name: mongodb
  # - name: moodle
  - name: mysql
  # - name: nginx
  - name: nodejs
  # - name: nodewebkit
  - name: oracle
  # - name: photoshop
  # - name: php
  # - name: phpstorm
  # - name: protractor
  # - name: postgresql
  # - name: python
  # - name: pycharm
  # - name: rails
  # - name: react
  # - name: redhat
  # - name: redis
  # - name: ruby
  # - name: rubymine
  - name: safari
  # - name: sass
  # - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  # - name: swift
  # - name: symfony
  - name: tomcat
  - name: travis
  # - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  # - name: visualstudio
  # - name: vuejs
  # - name: webpack
  # - name: webstorm
  - name: windows8
  # - name: wordpress
  # - name: yii
  # - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/iljun
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
